allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  d0c09ce6-16bf-463f-a405-6fd75158043d:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-09T14:23:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 70490114-3a4e-440b-a1b1-81eff1e9458d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 60dde785-c4f9-4891-b161-387b21002a05 # Описание
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 85ae46c8-addd-42c9-a541-afe8062197ba
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: abe9393f-d6fc-4d32-b15e-92d8e60ed556
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5970aef-f123-4189-ba1a-3802f8ec398e # Длительность
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 981464ba-de78-4871-a13a-554487344139
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a77256ae-08fb-4cc0-b98d-5438ddf86651 # Подборки
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78610bcc-5f23-4229-a2f6-418cee1058f5
            userCondition: null
            warning: null
            width: 100
        name: Данные
        uid: de874206-2f75-4b78-884e-b1d08752e6b8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 08ebc92f-64c7-4e05-822f-d862d2571ac5 # Обложка IRL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cef9813e-10c6-4e82-b597-9f1f2e28a7f6
            userCondition: null
            warning: null
            width: 100
        name: Изображения
        uid: 8f273bbd-8037-4f37-a9df-0706011be78a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f627c6c-2a63-4aa3-98d1-2ad6e5981b6f # Ссылки на просмотр
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 29a903ad-c7f2-4edd-877c-9624de354dbd
            userCondition: null
            warning: null
            width: 100
        name: Ссылки
        uid: 46e39cb6-76c2-457f-a987-438f6919376a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:27:25+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e9b57674-17c1-4dab-bc0b-a669153ba149 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d339141b-d7e1-448f-b5aa-bb3d10ab4574
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: b022a720-545a-4128-bcbf-74b23cd61ea4
        userCondition: null
    thumbFieldKey: null
handle: irl
hasTitleField: true
icon: camcorder
name: IRL
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
