allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  e4137a20-4869-49e4-b09f-37d5bdf05c0e:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-09T14:26:27+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa967582-a232-403d-ad6e-9ad510f5c781
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 67267b58-2e2e-43a4-a490-6ff33c5118eb
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:30:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d5970aef-f123-4189-ba1a-3802f8ec398e # Длительность
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d3e23988-9ac5-4d46-9b89-2ca3e0805f4b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-04-09T14:30:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a77256ae-08fb-4cc0-b98d-5438ddf86651 # Подборки
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de5f0193-5fbb-4afd-8b43-d4c4f2e500c6
            userCondition: null
            warning: null
            width: 100
        name: Данные
        uid: d8c93ce5-856d-4278-8bd6-9fbbb597331a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:30:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 30fe5b75-935c-46f8-80cc-0b5b51e1c481 # Обложка реакции
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37b06498-d121-4ceb-b5e4-5ee8978b4ca4
            userCondition: null
            warning: null
            width: 100
        name: Изображения
        uid: 332ba9e4-8eba-4854-b16e-249f70820b32
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:30:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4f627c6c-2a63-4aa3-98d1-2ad6e5981b6f # Ссылки на просмотр
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08e5a17d-025f-4fef-9fc9-c7ceb9833173
            userCondition: null
            warning: null
            width: 100
        name: Ссылки
        uid: 93b8f105-9845-44e9-87e2-17565d92cf3b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-04-09T14:30:06+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e9b57674-17c1-4dab-bc0b-a669153ba149 # SEO
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1e9d72fd-dbbe-4bfe-b61e-35152ea36302
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e90eb519-a822-4cf6-9760-828e36976ebd
        userCondition: null
    thumbFieldKey: null
handle: reaction
hasTitleField: true
icon: face-smile-upside-down
name: Реакция
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
