altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c11bc0f1-2cdd-45a5-bd3e-b1c466d18fc7:
    cardThumbAlignment: start
    cardView:
      - filename
      - imageSize
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-04-09T12:28:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: e2b6e18d-ddb5-4750-aee4-66f9fb32ba0c
            userCondition: null
            warning: null
            width: 100
        name: Контент
        uid: 449b0cc6-87f9-4039-9d38-91392a5d6adf
        userCondition: null
    thumbFieldKey: null
fs: irlCoversFs
handle: irlCover
name: 'Обложка IRL'
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
