columnSuffix: null
handle: movieCover
instructions: null
name: 'Обложка фильма'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:ba5e6aca-1a97-4949-97ac-5df4c35b8b5f' # Обложка фильма
  defaultUploadLocationSubpath: '{slug}'
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:13e4988e-def8-4a40-9a5c-315922192141' # Обложка аниме
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: false
  sources:
    - 'volume:ba5e6aca-1a97-4949-97ac-5df4c35b8b5f' # Обложка фильма
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
