columnSuffix: null
handle: reactionCover
instructions: null
name: 'Обложка реакции'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:29e7c515-bc75-4a45-99ff-4c9ba93bc41f' # Обложка реакции
  defaultUploadLocationSubpath: '{slug}'
  maintainHierarchy: false
  maxRelations: null
  minRelations: 0
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:13e4988e-def8-4a40-9a5c-315922192141' # Обложка аниме
  restrictedLocationSubpath: null
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: false
  sources:
    - 'volume:29e7c515-bc75-4a45-99ff-4c9ba93bc41f' # Обложка реакции
  targetSiteId: null
  validateRelatedElements: false
  viewMode: thumbs
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
