columnSuffix: null
handle: watchLinks
instructions: null
name: 'Ссылки на просмотр'
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: table
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - bee3b092-1b1e-47cb-b676-092ea0165aac # Ссылки на просмотр
        -
          - group
          - Общие
  includeTableView: false
  maxEntries: 1000
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
